# Data Wrangling with House Prices

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

### Load the data
Load the [House Prices](https://www.kaggle.com/competitions/house-prices-advanced-regression-techniques/overview) dataset from Kaggle. You may need to download the dataset and move it to your working location in order to read it in.


In [2]:
df = pd.read_csv('housing_train.csv')

In [3]:
df.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5   
2         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      9   
3         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
4         Lvl    AllPub  ...        0    NaN   NaN         NaN       0     12   

  YrSold  SaleType  SaleCondition  SalePrice  
0   2008        WD         Normal     208500  
1   2007        WD         Normal     181500  
2   2008        WD         Normal     223500  
3   2006        WD        Abnorml     140000  
4   2008        WD         Normal     250000  

[5 rows x 81 columns]

In [4]:
df.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive

In [5]:
df.dtypes

Id                 int64
MSSubClass         int64
MSZoning          object
LotFrontage      float64
LotArea            int64
                  ...   
MoSold             int64
YrSold             int64
SaleType          object
SaleCondition     object
SalePrice          int64
Length: 81, dtype: object

In [6]:
df.describe()

Id   MSSubClass  LotFrontage        LotArea  OverallQual  \
count  1460.000000  1460.000000  1201.000000    1460.000000  1460.000000   
mean    730.500000    56.897260    70.049958   10516.828082     6.099315   
std     421.610009    42.300571    24.284752    9981.264932     1.382997   
min       1.000000    20.000000    21.000000    1300.000000     1.000000   
25%     365.750000    20.000000    59.000000    7553.500000     5.000000   
50%     730.500000    50.000000    69.000000    9478.500000     6.000000   
75%    1095.250000    70.000000    80.000000   11601.500000     7.000000   
max    1460.000000   190.000000   313.000000  215245.000000    10.000000   

       OverallCond    YearBuilt  YearRemodAdd   MasVnrArea   BsmtFinSF1  ...  \
count  1460.000000  1460.000000   1460.000000  1452.000000  1460.000000  ...   
mean      5.575342  1971.267808   1984.865753   103.685262   443.639726  ...   
std       1.112799    30.202904     20.645407   181.066207   456.098091  ...   
min       1.000000  1872.000000   1950.000000     0.000000     0.000000  ...   
25%       5.000000  1954.000000   1967.000000     0.000000     0.000000  ...   
50%       5.000000  1973.000000   1994.000000     0.000000   383.500000  ...   
75%       6.000000  2000.000000   2004.000000   166.000000   712.250000  ...   
max       9.000000  2010.000000   2010.000000  1600.000000  5644.000000  ...   

        WoodDeckSF  OpenPorchSF  EnclosedPorch    3SsnPorch  ScreenPorch  \
count  1460.000000  1460.000000    1460.000000  1460.000000  1460.000000   
mean     94.244521    46.660274      21.954110     3.409589    15.060959   
std     125.338794    66.256028      61.119149    29.317331    55.757415   
min       0.000000     0.000000       0.000000     0.000000     0.000000   
25%       0.000000     0.000000       0.000000     0.000000     0.000000   
50%       0.000000    25.000000       0.000000     0.000000     0.000000   
75%     168.000000    68.000000       0.000000     0.000000     0.000000   
max     857.000000   547.000000     552.000000   508.000000   480.000000   

          PoolArea       MiscVal       MoSold       YrSold      SalePrice  
count  1460.000000   1460.000000  1460.000000  1460.000000    1460.000000  
mean      2.758904     43.489041     6.321918  2007.815753  180921.195890  
std      40.177307    496.123024     2.703626     1.328095   79442.502883  
min       0.000000      0.000000     1.000000  2006.000000   34900.000000  
25%       0.000000      0.000000     5.000000  2007.000000  129975.000000  
50%       0.000000      0.000000     6.000000  2008.000000  163000.000000  
75%       0.000000      0.000000     8.000000  2009.000000  214000.000000  
max     738.000000  15500.000000    12.000000  2010.000000  755000.000000  

[8 rows x 38 columns]

In [7]:
df.shape

(1460, 81)

### Split into X and Y

In [8]:
label = 'SalePrice'
Y = df[label]
X = df.drop(label, axis=1)

In [9]:
Y

0       208500
1       181500
2       223500
3       140000
4       250000
         ...  
1455    175000
1456    210000
1457    266500
1458    142125
1459    147500
Name: SalePrice, Length: 1460, dtype: int64

In [10]:
X

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0        1          60       RL         65.0     8450   Pave   NaN      Reg   
1        2          20       RL         80.0     9600   Pave   NaN      Reg   
2        3          60       RL         68.0    11250   Pave   NaN      IR1   
3        4          70       RL         60.0     9550   Pave   NaN      IR1   
4        5          60       RL         84.0    14260   Pave   NaN      IR1   
...    ...         ...      ...          ...      ...    ...   ...      ...   
1455  1456          60       RL         62.0     7917   Pave   NaN      Reg   
1456  1457          20       RL         85.0    13175   Pave   NaN      Reg   
1457  1458          70       RL         66.0     9042   Pave   NaN      Reg   
1458  1459          20       RL         68.0     9717   Pave   NaN      Reg   
1459  1460          20       RL         75.0     9937   Pave   NaN      Reg   

     LandContour Utilities  ... ScreenPorch PoolArea PoolQC  Fence  \
0            Lvl    AllPub  ...           0        0    NaN    NaN   
1            Lvl    AllPub  ...           0        0    NaN    NaN   
2            Lvl    AllPub  ...           0        0    NaN    NaN   
3            Lvl    AllPub  ...           0        0    NaN    NaN   
4            Lvl    AllPub  ...           0        0    NaN    NaN   
...          ...       ...  ...         ...      ...    ...    ...   
1455         Lvl    AllPub  ...           0        0    NaN    NaN   
1456         Lvl    AllPub  ...           0        0    NaN  MnPrv   
1457         Lvl    AllPub  ...           0        0    NaN  GdPrv   
1458         Lvl    AllPub  ...           0        0    NaN    NaN   
1459         Lvl    AllPub  ...           0        0    NaN    NaN   

     MiscFeature MiscVal MoSold  YrSold  SaleType  SaleCondition  
0            NaN       0      2    2008        WD         Normal  
1            NaN       0      5    2007        WD         Normal  
2            NaN       0      9    2008        WD         Normal  
3            NaN       0      2    2006        WD        Abnorml  
4            NaN       0     12    2008        WD         Normal  
...          ...     ...    ...     ...       ...            ...  
1455         NaN       0      8    2007        WD         Normal  
1456         NaN       0      2    2010        WD         Normal  
1457        Shed    2500      5    2010        WD         Normal  
1458         NaN       0      4    2010        WD         Normal  
1459         NaN       0      6    2008        WD         Normal  

[1460 rows x 80 columns]

### Pre-Split Dataset Manipulations

In [11]:
# Id is a redundant column and provides no modeling value
X = X.drop('Id', axis=1)

In [12]:
X.head()

MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0          60       RL         65.0     8450   Pave   NaN      Reg   
1          20       RL         80.0     9600   Pave   NaN      Reg   
2          60       RL         68.0    11250   Pave   NaN      IR1   
3          70       RL         60.0     9550   Pave   NaN      IR1   
4          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities LotConfig  ... ScreenPorch PoolArea PoolQC Fence  \
0         Lvl    AllPub    Inside  ...           0        0    NaN   NaN   
1         Lvl    AllPub       FR2  ...           0        0    NaN   NaN   
2         Lvl    AllPub    Inside  ...           0        0    NaN   NaN   
3         Lvl    AllPub    Corner  ...           0        0    NaN   NaN   
4         Lvl    AllPub       FR2  ...           0        0    NaN   NaN   

  MiscFeature MiscVal  MoSold  YrSold  SaleType  SaleCondition  
0         NaN       0       2    2008        WD         Normal  
1         NaN       0       5    2007        WD         Normal  
2         NaN       0       9    2008        WD         Normal  
3         NaN       0       2    2006        WD        Abnorml  
4         NaN       0      12    2008        WD         Normal  

[5 rows x 79 columns]

### Train/Test Split the Data

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=123)

## Transformers
* Standard Scaling
* Encoding
* Imputation

https://scikit-learn.org/stable/modules/preprocessing.html
https://scikit-learn.org/stable/modules/impute.html

Note: Do not apply transformations before train/test split


#### Scaling

In [14]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

In [15]:
from sklearn.datasets import fetch_california_housing

In [16]:
cali = fetch_california_housing()

In [17]:
X_cali = pd.DataFrame(cali.data, columns=cali.feature_names)
y_cali = cali.target

In [533]:
X_cali

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  
0        -122.23  
1        -122.22  
2        -122.24  
3        -122.25  
4        -122.25  
...          ...  
20635    -121.09  
20636    -121.21  
20637    -121.22  
20638    -121.32  
20639    -121.24  

[20640 rows x 8 columns]

In [534]:
from sklearn.linear_model import LinearRegression

In [535]:
reg = LinearRegression().fit(X_cali, y_cali)

In [536]:
reg.coef_

array([ 4.36693293e-01,  9.43577803e-03, -1.07322041e-01,  6.45065694e-01,
       -3.97638942e-06, -3.78654265e-03, -4.21314378e-01, -4.34513755e-01])

In [537]:
print(list(zip(reg.coef_.round(2), cali.feature_names)))

[(0.44, 'MedInc'), (0.01, 'HouseAge'), (-0.11, 'AveRooms'), (0.65, 'AveBedrms'), (-0.0, 'Population'), (-0.0, 'AveOccup'), (-0.42, 'Latitude'), (-0.43, 'Longitude')]


In [118]:
scaler = MinMaxScaler()

In [119]:
scaled = scaler.fit_transform(X_cali)
print(scaled)

[[0.53966842 0.78431373 0.0435123  ... 0.00149943 0.5674814  0.21115538]
 [0.53802706 0.39215686 0.03822395 ... 0.00114074 0.565356   0.21215139]
 [0.46602805 1.         0.05275646 ... 0.00169796 0.5642933  0.21015936]
 ...
 [0.08276438 0.31372549 0.03090386 ... 0.0013144  0.73219979 0.31175299]
 [0.09429525 0.33333333 0.03178269 ... 0.0011515  0.73219979 0.30179283]
 [0.13025338 0.29411765 0.03125246 ... 0.00154886 0.72582359 0.30976096]]


In [120]:
reg = LinearRegression().fit(scaled, y_cali)
reg.coef_
print(list(zip(reg.coef_.round(2), cali.feature_names)))

[(6.33, 'MedInc'), (0.48, 'HouseAge'), (-15.14, 'AveRooms'), (21.76, 'AveBedrms'), (-0.14, 'Population'), (-4.71, 'AveOccup'), (-3.96, 'Latitude'), (-4.36, 'Longitude')]


In [539]:
scaler.fit_transform(X_cali)

array([[ 2.34476576,  0.98214266,  0.62855945, ..., -0.04959654,
         1.05254828, -1.32783522],
       [ 2.33223796, -0.60701891,  0.32704136, ..., -0.09251223,
         1.04318455, -1.32284391],
       [ 1.7826994 ,  1.85618152,  1.15562047, ..., -0.02584253,
         1.03850269, -1.33282653],
       ...,
       [-1.14259331, -0.92485123, -0.09031802, ..., -0.0717345 ,
         1.77823747, -0.8237132 ],
       [-1.05458292, -0.84539315, -0.04021111, ..., -0.09122515,
         1.77823747, -0.87362627],
       [-0.78012947, -1.00430931, -0.07044252, ..., -0.04368215,
         1.75014627, -0.83369581]])

In [538]:
scaler = StandardScaler()
scaled = scaler.fit_transform(X_cali)
print(scaled)

[[ 2.34476576  0.98214266  0.62855945 ... -0.04959654  1.05254828
  -1.32783522]
 [ 2.33223796 -0.60701891  0.32704136 ... -0.09251223  1.04318455
  -1.32284391]
 [ 1.7826994   1.85618152  1.15562047 ... -0.02584253  1.03850269
  -1.33282653]
 ...
 [-1.14259331 -0.92485123 -0.09031802 ... -0.0717345   1.77823747
  -0.8237132 ]
 [-1.05458292 -0.84539315 -0.04021111 ... -0.09122515  1.77823747
  -0.87362627]
 [-0.78012947 -1.00430931 -0.07044252 ... -0.04368215  1.75014627
  -0.83369581]]


#### Ordinal Encoding

Note: LabelEncoder() is intended for target classes and may cause errors if used on your X features

In [540]:
from sklearn.preprocessing import OrdinalEncoder

In [541]:
from sklearn.datasets import load_diabetes

In [542]:
diabetes = load_diabetes(scaled=False, as_frame=True)
X_diabetes = pd.DataFrame(diabetes.data, columns=diabetes.feature_names)
y_diabetes = diabetes.target

In [543]:
# create categorical columns
X_diabetes['Education'] = np.random.choice(a=['Graduate', 'High School', 'Other'], size=len(X_diabetes), p=[.5, .3, .2])

X_diabetes['Hobby'] = np.random.choice(a=['Pythonathon', 'Golf', 'Extreme Cliff Diving'], size=len(X_diabetes), p=[.7, .2, .1])

X_diabetes['VideoGame'] = np.random.choice(a=['Halo', 'Smash Bros', 'ARK', None], size=len(X_diabetes), p=[.1, .2, .2, .5])

In [544]:
X_diabetes

age  sex   bmi      bp     s1     s2    s3    s4      s5     s6  \
0    59.0  2.0  32.1  101.00  157.0   93.2  38.0  4.00  4.8598   87.0   
1    48.0  1.0  21.6   87.00  183.0  103.2  70.0  3.00  3.8918   69.0   
2    72.0  2.0  30.5   93.00  156.0   93.6  41.0  4.00  4.6728   85.0   
3    24.0  1.0  25.3   84.00  198.0  131.4  40.0  5.00  4.8903   89.0   
4    50.0  1.0  23.0  101.00  192.0  125.4  52.0  4.00  4.2905   80.0   
..    ...  ...   ...     ...    ...    ...   ...   ...     ...    ...   
437  60.0  2.0  28.2  112.00  185.0  113.8  42.0  4.00  4.9836   93.0   
438  47.0  2.0  24.9   75.00  225.0  166.0  42.0  5.00  4.4427  102.0   
439  60.0  2.0  24.9   99.67  162.0  106.6  43.0  3.77  4.1271   95.0   
440  36.0  1.0  30.0   95.00  201.0  125.2  42.0  4.79  5.1299   85.0   
441  36.0  1.0  19.6   71.00  250.0  133.2  97.0  3.00  4.5951   92.0   

       Education        Hobby   VideoGame  
0          Other  Pythonathon         ARK  
1       Graduate  Pythonathon         ARK  
2          Other         Golf        None  
3    High School  Pythonathon        None  
4       Graduate  Pythonathon        None  
..           ...          ...         ...  
437     Graduate  Pythonathon         ARK  
438     Graduate  Pythonathon        None  
439        Other  Pythonathon        None  
440     Graduate  Pythonathon        None  
441     Graduate  Pythonathon  Smash Bros  

[442 rows x 13 columns]

In [545]:
# The target data, namely a quantitative measure of disease progression one year after baseline
y_diabetes.value_counts()

200.0    6
72.0     6
90.0     5
178.0    5
71.0     5
        ..
73.0     1
222.0    1
86.0     1
79.0     1
57.0     1
Name: target, Length: 214, dtype: int64

In [546]:
X_diabetes_train, X_diabetes_test, y_diabetes_train, y_diabetes_test = train_test_split(X_diabetes, y_diabetes, test_size=0.2, random_state=seed)

In [547]:
X_diabetes_train[['Education']]

Education
138     Graduate
382     Graduate
351     Graduate
373     Graduate
192     Graduate
..           ...
204        Other
53      Graduate
294        Other
211  High School
303  High School

[353 rows x 1 columns]

In [553]:
enc = OrdinalEncoder()

In [554]:
enc.fit(X_diabetes_train[['Education']])

OrdinalEncoder()

In [555]:
enc.categories_

[array(['Graduate', 'High School', 'Other'], dtype=object)]

In [558]:
enc.inverse_transform([[2]])

array([['Other']], dtype=object)

In [559]:
enc =  OrdinalEncoder(categories=[['Other', 'High School', 'Graduate']])

In [560]:
enc.fit_transform(X_diabetes_train[['Education']])

array([[2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [1.],
       [1.],
       [2.],
       [2.],
       [2.],
       [1.],
       [1.],
       [2.],
       [1.],
       [2.],
       [1.],
       [1.],
       [2.],
       [1.],
       [1.],
       [2.],
       [2.],
       [1.],
       [1.],
       [2.],
       [2.],
       [2.],
       [0.],
       [2.],
       [0.],
       [2.],
       [2.],
       [1.],
       [2.],
       [1.],
       [2.],
       [2.],
       [0.],
       [2.],
       [1.],
       [2.],
       [2.],
       [2.],
       [0.],
       [2.],
       [1.],
       [1.],
       [2.],
       [2.],
       [0.],
       [1.],
       [2.],
       [1.],
       [2.],
       [0.],
       [2.],
       [0.],
       [2.],
       [0.],
       [1.],
       [2.],
       [1.],
       [1.],
       [2.],
       [2.],
       [0.],
       [2.],
       [1.],
       [2.],
       [2.],
       [2.],
       [1.],
       [1.],
       [2.],
       [0.],
       [0.],

In [561]:
enc.categories_

[array(['Other', 'High School', 'Graduate'], dtype=object)]

In [564]:
enc.inverse_transform([[2]])

array([['Graduate']], dtype=object)

In [565]:
enc.transform(X_diabetes_test[['Education']])

array([[2.],
       [1.],
       [2.],
       [0.],
       [2.],
       [0.],
       [2.],
       [1.],
       [2.],
       [0.],
       [2.],
       [2.],
       [0.],
       [1.],
       [1.],
       [0.],
       [2.],
       [2.],
       [1.],
       [2.],
       [0.],
       [0.],
       [1.],
       [1.],
       [2.],
       [2.],
       [0.],
       [1.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [2.],
       [1.],
       [2.],
       [1.],
       [2.],
       [1.],
       [2.],
       [2.],
       [0.],
       [2.],
       [1.],
       [0.],
       [0.],
       [1.],
       [2.],
       [2.],
       [2.],
       [2.],
       [0.],
       [2.],
       [2.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [2.],
       [2.],
       [2.],
       [2.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [2.],
       [2.],
       [1.],
       [2.],
       [0.],
       [2.],
       [0.],

#### One Hot Encoding

In [566]:
from sklearn.preprocessing import OneHotEncoder

In [567]:
ohe_enc = OneHotEncoder(handle_unknown='ignore')

In [568]:
ohe_enc.fit(X_diabetes_train[['Hobby']])

OneHotEncoder(handle_unknown='ignore')

In [570]:
ohe_enc.categories_

[array(['Extreme Cliff Diving', 'Golf', 'Pythonathon'], dtype=object)]

In [571]:
ohe_enc.transform(X_diabetes_train[['Hobby']]).toarray()

array([[0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       ...,
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.]])

#### Imputation

In [574]:
from sklearn.impute import SimpleImputer

In [575]:
X_diabetes_train['VideoGame']

138    Smash Bros
382          None
351           ARK
373    Smash Bros
192           ARK
          ...    
204          None
53            ARK
294          None
211           ARK
303          None
Name: VideoGame, Length: 353, dtype: object

Note: Make sure you know which type of missing values you have, default is np.nan

In [581]:
imp_mean = SimpleImputer(missing_values=None, strategy='most_frequent')

In [582]:
imp_mean.fit(X_diabetes_train[['VideoGame']])

SimpleImputer(strategy='most_frequent')

In [583]:
imp_mean.transform(X_diabetes_train[['VideoGame']])

array([['Smash Bros'],
       [None],
       ['ARK'],
       ['Smash Bros'],
       ['ARK'],
       [None],
       ['ARK'],
       [None],
       [None],
       ['Smash Bros'],
       ['Smash Bros'],
       ['Smash Bros'],
       ['ARK'],
       [None],
       ['ARK'],
       [None],
       [None],
       [None],
       [None],
       ['ARK'],
       [None],
       [None],
       ['Smash Bros'],
       ['ARK'],
       [None],
       ['Smash Bros'],
       ['Smash Bros'],
       [None],
       [None],
       [None],
       ['Smash Bros'],
       [None],
       [None],
       ['Halo'],
       [None],
       ['Smash Bros'],
       [None],
       ['Halo'],
       ['ARK'],
       [None],
       [None],
       ['ARK'],
       [None],
       [None],
       [None],
       [None],
       ['Smash Bros'],
       [None],
       ['Halo'],
       ['ARK'],
       [None],
       ['ARK'],
       [None],
       [None],
       [None],
       ['Smash Bros'],
       [None],
       [None],
       [None],
  

In [580]:
imp_mean.transform(X_diabetes_test[['VideoGame']])

array([['ARK'],
       ['ARK'],
       ['Smash Bros'],
       ['Halo'],
       ['Smash Bros'],
       ['ARK'],
       ['Smash Bros'],
       ['ARK'],
       ['ARK'],
       ['ARK'],
       ['ARK'],
       ['ARK'],
       ['ARK'],
       ['ARK'],
       ['Smash Bros'],
       ['ARK'],
       ['ARK'],
       ['ARK'],
       ['ARK'],
       ['Halo'],
       ['ARK'],
       ['Smash Bros'],
       ['ARK'],
       ['ARK'],
       ['Smash Bros'],
       ['Halo'],
       ['ARK'],
       ['ARK'],
       ['ARK'],
       ['Smash Bros'],
       ['ARK'],
       ['ARK'],
       ['ARK'],
       ['ARK'],
       ['ARK'],
       ['ARK'],
       ['ARK'],
       ['ARK'],
       ['Halo'],
       ['ARK'],
       ['ARK'],
       ['ARK'],
       ['Smash Bros'],
       ['ARK'],
       ['Halo'],
       ['ARK'],
       ['ARK'],
       ['Halo'],
       ['ARK'],
       ['Halo'],
       ['ARK'],
       ['ARK'],
       ['ARK'],
       ['ARK'],
       ['ARK'],
       ['ARK'],
       ['ARK'],
       ['ARK'],
       ['

## Pipelining Transformations

In [584]:
from sklearn.pipeline import Pipeline
from sklearn.pipeline import make_pipeline
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestClassifier

In [585]:
X_train

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
98                 5.1               2.5                3.0               1.1
126                6.2               2.8                4.8               1.8
40                 5.0               3.5                1.3               0.3
133                6.3               2.8                5.1               1.5
77                 6.7               3.0                5.0               1.7
..                 ...               ...                ...               ...
143                6.8               3.2                5.9               2.3
116                6.5               3.0                5.5               1.8
53                 5.5               2.3                4.0               1.3
38                 4.4               3.0                1.3               0.2
47                 4.6               3.2                1.4               0.2

[120 rows x 4 columns]

In [586]:
y_train

target
98        1
126       2
40        0
133       2
77        1
..      ...
143       2
116       2
53        1
38        0
47        0

[120 rows x 1 columns]

In [248]:
pipe = make_pipeline(StandardScaler(), RandomForestClassifier(max_depth=3, random_state=0))

In [587]:
pipe.fit(X_train, y_train)

/usr/local/lib/python3.9/site-packages/sklearn/pipeline.py:382: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self._final_estimator.fit(Xt, y, **fit_params_last_step)


Pipeline(steps=[('standardscaler', StandardScaler()),
                ('randomforestclassifier',
                 RandomForestClassifier(max_depth=3, random_state=0))])

In [588]:
pipe.score(X_test, y_test)

1.0

Applying Different Transformation to Different Columns

In [589]:
X_diabetes_train

age  sex   bmi     bp     s1     s2    s3   s4      s5     s6  \
138  58.0  2.0  36.7  117.0  166.0   93.8  44.0  4.0  4.9488  109.0   
382  62.0  1.0  32.0   88.0  172.0   69.0  38.0  4.0  5.7838  100.0   
351  25.0  2.0  22.6   85.0  130.0   71.0  48.0  3.0  4.0073   81.0   
373  28.0  1.0  25.4   93.0  141.0   79.0  49.0  3.0  4.1744   91.0   
192  64.0  2.0  23.5   97.0  203.0  129.0  59.0  3.0  4.3175   77.0   
..    ...  ...   ...    ...    ...    ...   ...  ...     ...    ...   
204  79.0  2.0  27.0  103.0  169.0  110.8  37.0  5.0  4.6634  110.0   
53   46.0  1.0  24.9  115.0  198.0  129.6  54.0  4.0  4.2767  103.0   
294  55.0  2.0  23.5   93.0  177.0  126.8  41.0  4.0  3.8286   83.0   
211  74.0  1.0  29.8  101.0  171.0  104.8  50.0  3.0  4.3944   86.0   
303  69.0  1.0  29.6  122.0  231.0  128.4  56.0  4.0  5.4510   86.0   

       Education                 Hobby   VideoGame  
138     Graduate           Pythonathon  Smash Bros  
382     Graduate                  Golf        None  
351     Graduate                  Golf         ARK  
373     Graduate           Pythonathon  Smash Bros  
192     Graduate           Pythonathon         ARK  
..           ...                   ...         ...  
204        Other           Pythonathon        None  
53      Graduate  Extreme Cliff Diving         ARK  
294        Other  Extreme Cliff Diving        None  
211  High School           Pythonathon         ARK  
303  High School           Pythonathon        None  

[353 rows x 13 columns]

In [590]:
numeric_cols = ['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6']

ordinal_cols = ['Education']

ohe_cols = ['Hobby', 'VideoGame']

In [591]:
# Build the pipeline
numeric_transformer = Pipeline(steps=[
    ('impute', SimpleImputer(strategy='mean')),
    ('scale', MinMaxScaler())
])

ordinal_transformer = Pipeline(steps=[
    ('impute', SimpleImputer(strategy='constant')),
    ('encode', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1)),
])

ohe_transformer = Pipeline(steps=[
    ('impute', SimpleImputer(strategy='constant')),
    ('encode', OneHotEncoder(handle_unknown='ignore')),
])

preprocessor = ColumnTransformer(
    transformers=[
        ('numeric', numeric_transformer, numeric_cols),
        ('ordinal', ordinal_transformer, ordinal_cols),
        ('ohe', ohe_transformer, ohe_cols),
    ],
)

pipeline = Pipeline(steps=[
    ('preprocessing', preprocessor),
    ('linear_regression', LinearRegression())
])

In [592]:
pipeline.fit(X_diabetes_train, y_diabetes_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('numeric',
                                                  Pipeline(steps=[('impute',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scale',
                                                                   MinMaxScaler())]),
                                                  ['age', 'sex', 'bmi', 'bp',
                                                   's1', 's2', 's3', 's4', 's5',
                                                   's6']),
                                                 ('ordinal',
                                                  Pipeline(steps=[('impute',
                                                                   SimpleImputer(strategy='constant')),
                                                                  ('encode',
                                                                   OrdinalEncoder(handle_unknown='use_encoded_value',
                                                                                  unknown_value=-1))]),
                                                  ['Education']),
                                                 ('ohe',
                                                  Pipeline(steps=[('impute',
                                                                   SimpleImputer(strategy='constant')),
                                                                  ('encode',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['Hobby', 'VideoGame'])])),
                ('linear_regression', LinearRegression())])

In [594]:
pipeline.predict(X_diabetes_test)

array([150.32013255, 187.76458478,  98.45066798,  73.97283766,
        92.43346964, 200.68777709, 148.37119918, 134.52585889,
       116.18049824, 150.5033249 ,  52.30436127, 251.01932236,
       195.15749339, 149.17769507, 137.51721669, 146.10006022,
       122.9973894 , 128.49650052, 251.7716527 , 144.08987561,
       111.79832173, 144.42972432, 153.93279856, 270.61153871,
       239.24161605, 219.18103357,  63.39935331, 264.68032743,
       144.70416141,  85.876012  , 146.27730929, 152.68131366,
       129.99786488,  92.88137482, 166.11387653, 301.49741127,
       251.23425197,  58.5620688 , 204.2417913 ,  91.04324297,
       208.04334   , 136.04057119, 155.38868568, 134.83368773,
       164.38058298, 152.65196404,  87.07118413, 218.61695252,
       111.35302554, 176.39409245, 125.57041805, 160.73060532,
       180.82601125,  99.55379315, 134.16096107, 146.88519006,
       215.68929615, 145.35000964, 267.97599758, 116.17960817,
        97.98636731, 213.52640693, 187.10470398, 197.73

In [595]:
preds = pipeline.predict(X_diabetes_test)

In [596]:
from sklearn.metrics import mean_squared_error
from math import sqrt

rmse = sqrt(mean_squared_error(y_diabetes_test, preds))
rmse

54.75151649134907

## Putting it All Together
* Load the data
* Train/Test Split
* Transform in a Pipeline
* Fit the Model Pipeline
* Evaluate best_estimator on test set